import { ExerciseProps } from '../interfaces/exerciseProps.js';

export const exercise: ExerciseProps[] = [
  {
    id: 1,
    title: 'Abdominal',
    types: [
      { id: 0, type: 'Abdominal', exercise: 'Abdominal' },
      { id: 1, type: 'Abdominal', exercise: 'Abdominal com rolo no chão' },
      { id: 2, type: 'Abdominal', exercise: 'Abdominal em V na máquina' },
      { id: 3, type: 'Abdominal', exercise: 'Abdominal na bola' },
      { id: 4, type: 'Abdominal', exercise: 'Abdominal no solo com elevação de pernas semidobradas' },
      { id: 5, type: 'Abdominal', exercise: 'Abdominal oblíquo rotação russa com anilha e pernas para cima' },
      { id: 6, type: 'Abdominal', exercise: 'Abdominal oblíquo rotação russa de quadril' },
      { id: 7, type: 'Abdominal', exercise: 'Abdominal oblíquo rotação sentado no banco com barra' },
      { id: 8, type: 'Abdominal', exercise: 'Abdominal sentado no banco com elevação de pernas' },
      { id: 9, type: 'Abdominal', exercise: 'Abdominal supra' },
    ]
  },
  {
    id: 2,
    title: 'Antebraço',
    types: [
      { id: 0, type: 'Antebraço', exercise: 'Rosca Inversa de Punho com Halter em Banco com um Braço' },
      { id: 1, type: 'Antebraço', exercise: 'Rosca punho com barra' },
      { id: 2, type: 'Antebraço', exercise: 'Rosca punho com barra atrás da costa' },
      { id: 3, type: 'Antebraço', exercise: 'Rosca punho com halter' },
      { id: 4, type: 'Antebraço', exercise: 'Rosca punho Neutra com Halter Sentado, com um braço' }
    ]
  },
  {
    id: 3,
    title: 'Bíceps',
    types: [
      { id: 0, type: 'Bíceps', exercise: 'Rosca aberta na barra com pegada aberta' },
      { id: 1, type: 'Bíceps', exercise: 'Rosca com halteres no banco inclinado' },
      { id: 2, type: 'Bíceps', exercise: 'Rosca concentrada unilateral com halter' },
      { id: 3, type: 'Bíceps', exercise: 'Rosca direta com barra e pegada fechada' },
      { id: 4, type: 'Bíceps', exercise: 'Rosca direta com halteres' },
      { id: 5, type: 'Bíceps', exercise: 'Rosca direta na barra EZ' },
      { id: 6, type: 'Bíceps', exercise: 'Rosca martelo com halteres' },
      { id: 7, type: 'Bíceps', exercise: 'Rosca no banco Scott com barra W' },
      { id: 8, type: 'Bíceps', exercise: 'Rosca no banco Scott com halteres' },
      { id: 9, type: 'Bíceps', exercise: 'Rosca no cabo usando a corda' },
      { id: 10, type: 'Bíceps', exercise: 'Rosca Scott com halter unilateral' },
    ]
  },
  {
    id: 4,
    title: 'Costa',
    types: [
      { id: 3, type: 'Costa', exercise: 'Barra fixa chin up com pegada aberta supinada' },
      { id: 2, type: 'Costa', exercise: 'Barra fixa chin up com pegada fechada' },
      { id: 5, type: 'Costa', exercise: 'Desenvolvendo as costas e o tronco em V' },
      { id: 4, type: 'Costa', exercise: 'Remada cavalinho' },
      { id: 7, type: 'Costa', exercise: 'Remada curvada com barra e pegada pronada' },
      { id: 8, type: 'Costa', exercise: 'Remada curvada com barra e pegada invertida supinada' },
      { id: 9, type: 'Costa', exercise: 'Remada no banco inclinado com halteres' },
      { id: 1, type: 'Costa', exercise: 'Remada sentado com cabo e triângulo' },
      { id: 0, type: 'Costa', exercise: 'Remada unilateral com halter serrote no banco' },
      { id: 11, type: 'Costa', exercise: 'Puxada com barra no pulley' },
      { id: 6, type: 'Costa', exercise: 'Puxada com pegada fechada no pulley' },
      { id: 10, type: 'Costa', exercise: 'Puxada pela frente com o triângulo no pulley' },
    ]
  },
  {
    id: 5,
    title: 'Glúteos',
    types: [
      { id: 0, type: 'Glúteos', exercise: 'Coice no cabo' },
      { id: 1, type: 'Glúteos', exercise: 'Extensão de quadril com perna dobrada' },
      { id: 2, type: 'Glúteos', exercise: 'Quatro apoios com elevação da perna' },
      { id: 3, type: 'Glúteos', exercise: 'Quatro apoios com perna esticada e elevação da perna' },
      { id: 4, type: 'Glúteos', exercise: 'Quatro apoios elevando braço e perna alternados' },
      { id: 5, type: 'Glúteos', exercise: 'Ponte com uma perna só elevada e reta' },
      { id: 6, type: 'Glúteos', exercise: 'Stiff com halteres' },
      { id: 7, type: 'Glúteos', exercise: 'Três apoios para glúteos e pernas' },
    ]
  },
  {
    id: 6,
    title: 'Ombro',
    types: [
      { id: 0, type: 'Ombro', exercise: 'Crucifixo invertido com halteres' },
      { id: 1, type: 'Ombro', exercise: 'Desenvolvimento Arnold' },
      { id: 2, type: 'Ombro', exercise: 'Desenvolvimento frontal com barra' },
      { id: 3, type: 'Ombro', exercise: 'Desenvolvimento para ombros com halteres' },
      { id: 4, type: 'Ombro', exercise: 'Elevação lateral de ombros com halteres' },
      { id: 5, type: 'Ombro', exercise: 'Remada alta em pé com halteres' },
      { id: 6, type: 'Ombro', exercise: 'Remada alta no cabo' },
      { id: 7, type: 'Ombro', exercise: 'Remada alta no Smith' },
      { id: 8, type: 'Ombro', exercise: 'Voador invertido na máquina peck deck' },
      { id: 9, type: 'Ombro', exercise: 'Encolhimento com Barra' },
      { id: 10, type: 'Ombro', exercise: 'Encolhimento com halteres' },
    ]
  },
  {
    id: 7,
    title: 'Panturrilha',
    types: [
      { id: 0, type: 'Panturrilha', exercise: 'Panturrilha apoiado no banco' },
      { id: 1, type: 'Panturrilha', exercise: 'Panturrilha com barra nos ombros' },
      { id: 2, type: 'Panturrilha', exercise: 'Panturrilha donkey' },
      { id: 3, type: 'Panturrilha', exercise: 'Panturrilha em pé com uma perna e apoio' },
      { id: 4, type: 'Panturrilha', exercise: 'Panturrilha em pé no aparelho' },
      { id: 5, type: 'Panturrilha', exercise: 'Panturrilha em pé no smith' },
      { id: 6, type: 'Panturrilha', exercise: 'Panturrilha em pé no step' },
      { id: 7, type: 'Panturrilha', exercise: 'Panturrilha no leg press' },
      { id: 8, type: 'Panturrilha', exercise: 'Panturrilha sentado com barra' },
      { id: 9, type: 'Panturrilha', exercise: 'Panturrilha sentado com halteres apoiados na perna' },
      { id: 10, type: 'Panturrilha', exercise: 'Panturrilha unilateral de panturrilha com o peso do corpo' },
    ]
  },
  {
    id: 8,
    title: 'Peito',
    types: [
      { id: 0, type: 'Peito', exercise: 'Crucifixo reto' },
      { id: 1, type: 'Peito', exercise: 'Flexão de braços' },
      { id: 2, type: 'Peito', exercise: 'Flexão de braços inclinada no banco' },
      { id: 3, type: 'Peito', exercise: 'Peck deck' },
      { id: 4, type: 'Peito', exercise: 'Pullover com barra' },
      { id: 5, type: 'Peito', exercise: 'Pullover com halter e braços estendidos com pernas a 90 graus' },
      { id: 6, type: 'Peito', exercise: 'Pullover com halter e braços esticados apoiado na lateral do banco' },
      { id: 7, type: 'Peito', exercise: 'Supino com pegada fechada na barra reta' },
      { id: 8, type: 'Peito', exercise: 'Supino inclinado com barra' },
      { id: 9, type: 'Peito', exercise: 'Supino inclinado com halteres' },
      { id: 10, type: 'Peito', exercise: 'Supino reto' },
      { id: 11, type: 'Peito', exercise: 'Supino reto com halteres' },
      { id: 12, type: 'Peito', exercise: 'Voador no cabo no banco inclinado' },
    ]
  },
  {
    id: 9,
    title: 'Perna',
    types: [
      { id: 0, type: 'Perna', exercise: 'Abdução de pernas deitado no solo e elevando a perna' },
      { id: 1, type: 'Perna', exercise: 'Abdução de pernas na máquina' },
      { id: 2, type: 'Perna', exercise: 'Abdução de pernas na máquina com cabos' },
      { id: 3, type: 'Perna', exercise: 'Adução de pernas na máquina' },
      { id: 4, type: 'Perna', exercise: 'Adução na máquina com cabos' },
      { id: 5, type: 'Perna', exercise: 'Agachamento afundo com barra' },
      { id: 6, type: 'Perna', exercise: 'Agachamento afundo no smith machine' },
      { id: 7, type: 'Perna', exercise: 'Agachamento afundo no step' },
      { id: 8, type: 'Perna', exercise: 'Agachamento avanço afundo com halteres' },
      { id: 9, type: 'Perna', exercise: 'Agachamento avanço afundo invertido com halteres' },
      { id: 10, type: 'Perna', exercise: 'Agachamento búlgaro no Smith' },
      { id: 11, type: 'Perna', exercise: 'Agachamento com barra' },
      { id: 12, type: 'Perna', exercise: 'Agachamento com barra apoiada no peito' },
      { id: 13, type: 'Perna', exercise: 'Agachamento com barra em postura ampla' },
      { id: 14, type: 'Perna', exercise: 'Agachamento com halteres' },
      { id: 15, type: 'Perna', exercise: 'Agachamento no Smith machine' },
      { id: 16, type: 'Perna', exercise: 'Agachamento no Smith machine com foco nos glúteos e posteriores da coxa' },
      { id: 17, type: 'Perna', exercise: 'Agachamento no hack' },
      { id: 18, type: 'Perna', exercise: 'Agachamento frontal com barra' },
      { id: 19, type: 'Perna', exercise: 'Agachamento lateral lunges com pesos kettlebell' },
      { id: 20, type: 'Perna', exercise: 'Agachamento livre' },
      { id: 21, type: 'Perna', exercise: 'Extensão de pernas na máquina' },
      { id: 22, type: 'Perna', exercise: 'Flexão de pernas na máquina' },
      { id: 23, type: 'Perna', exercise: 'Leg press 45 graus' },
      { id: 24, type: 'Perna', exercise: 'Leg press 45 graus com pernas flexionadas no peito' },
      { id: 25, type: 'Perna', exercise: 'Leg press 45 graus unilateral' },
      { id: 26, type: 'Perna', exercise: 'Levantamento terra deadlift com barra' },
    ]
  },
  {
    id: 10,
    title: 'Tríceps',
    types: [
      { id: 0, type: 'Tríceps', exercise: 'Flexão de braços com apoio do antebraço no chão' },
      { id: 1, type: 'Tríceps', exercise: 'Flexão diamante' },
      { id: 2, type: 'Tríceps', exercise: 'Tríceps apoiado no banco' },
      { id: 3, type: 'Tríceps', exercise: 'Tríceps com halteres no banco reto' },
      { id: 4, type: 'Tríceps', exercise: 'Tríceps em pé com halter na nuca' },
      { id: 5, type: 'Tríceps', exercise: 'Tríceps mergulho' },
      { id: 6, type: 'Tríceps', exercise: 'Tríceps na máquina de cabos usando a corda atrás da cabeça' },
      { id: 7, type: 'Tríceps', exercise: 'Tríceps puxada no pulley pegada pronada' },
      { id: 8, type: 'Tríceps', exercise: 'Tríceps puxada no pulley usando a corda' },
      { id: 9, type: 'Tríceps', exercise: 'Tríceps sentado no aparelho' },
      { id: 10, type: 'Tríceps', exercise: 'Tríceps testa' },
      { id: 11, type: 'Tríceps', exercise: 'Tríceps testa no banco inclinado e barra EZ' },
    ]
  },
];